Static (#12)
* Added output: 'export' in next.config.js

* Removed out headers() from next.config.js

* Changed Image.tsx to use a standard <img> tag

* Removed redirects

Error: Specified "redirects" cannot be used with "output: export". See more info here: https://nextjs.org/docs/messages/export-no-custom-routes

* Revert "Changed Image.tsx to use a standard <img> tag"

This reverts commit f11476b5a168122b42496673b9c1478494a47026.

* Changed to <img/> tag

* Revert "Changed to <img/> tag"

This reverts commit 0a57794e3e338619031583df4b57c9ae8368231e.

* Set images to unoptimized

* Added _redirects for Cloudflare Pages

* Update _redirects using placeholders

* Revert "Update _redirects using placeholders"

This reverts commit 26d6213f4b31de8cbd908fbbae82e27ad231f1f9.

* Fixed /PDFReader/ redirects

* Changed comment provider to disqus

* Revert "Changed comment provider to disqus"

This reverts commit 75cf79ad342c9e4b2bcc289aa520d0d82165791e.

* Removed unused ContentSecurityPolicy